- name: Get installed services
  ansible.builtin.service_facts:

- name: Check if Wazuh Agent service is installed
  set_fact:
    service_exists: "{{ 'wazuh-agent.service' in ansible_facts.services }}"

# --- Debian/Ubuntu ---

- name: Ensure GPG is installed (Debian)
  apt:
    name: gnupg
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure apt-transport-https is installed (Debian)
  apt:
    name: apt-transport-https
    state: present
  when: ansible_os_family == "Debian"

- name: Add Wazuh repository GPG key (Debian)
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present
  when: ansible_os_family == "Debian" and not service_exists

- name: Add Wazuh repository (Debian)
  apt_repository:
    repo: 'deb https://packages.wazuh.com/4.x/apt/ stable main'
    state: present
  when: ansible_os_family == "Debian" and not service_exists

- name: Update apt cache (Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian" and not service_exists

- name: Install Wazuh agent (Debian)
  apt:
    name: wazuh-agent
    state: present
  environment:
    WAZUH_MANAGER: '{{ wazuh_manager }}'
    WAZUH_AGENT_NAME: '{{ wazuh_agent_name }}'
    WAZUH_AGENT_GROUP: '{{ wazuh_agent_group }}'
  when: ansible_os_family == "Debian" and not service_exists

# --- Fedora/RedHat ---

- name: Import Wazuh GPG key (Fedora)
  ansible.builtin.rpm_key:
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present
  when: ansible_os_family == "RedHat" and not service_exists

- name: Add Wazuh repository (Fedora)
  ansible.builtin.yum_repository:
    name: wazuh
    description: Wazuh repository
    baseurl: https://packages.wazuh.com/4.x/yum/
    gpgcheck: yes
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    enabled: yes
  when: ansible_os_family == "RedHat" and not service_exists

- name: Install python3-libdnf5 for Ansible dnf module (Fedora)
  ansible.builtin.command:
    cmd: dnf install -y python3-libdnf5
  when: ansible_os_family == "RedHat" and not service_exists

- name: Install Wazuh agent (Fedora)
  dnf:
    name: wazuh-agent
    state: present
  environment:
    WAZUH_MANAGER: '{{ wazuh_manager }}'
    WAZUH_AGENT_NAME: '{{ wazuh_agent_name }}'
    WAZUH_AGENT_GROUP: '{{ wazuh_agent_group }}'
  when: ansible_os_family == "RedHat" and not service_exists

# --- Common ---

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes
  when: not service_exists

- name: Enable and start Wazuh agent service
  systemd:
    name: wazuh-agent
    enabled: yes
    state: started