---
- name: Allow Outbound HTTPS
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ panos_provider }}"
    rule_name: "Outbound_HTTPS"
    source_zone: ["internal"]
    source_ip: ["Internal_Net"]
    destination_zone: ["external"]
    destination_ip: ["any"]
    application: "{{ app_type_mappings.fw_https.palo_apps }}"
    service: "{{ app_type_mappings.fw_https.palo_service }}"
    action: "allow"
