---
- name: Set up palo-alto2 tunnel
  hosts: ubuntu-wkst
  roles:
    - palo2_ssh_tunnel

- name: Rotate passwords
  hosts: firewalls

  vars:
    use_default_creds: true

  collections:
    - paloaltonetworks.panos

  roles:
    - role: palo_rotate_creds
