---
- name: Set up palo-alto2 tunnel
  hosts: ubuntu-wkst
  roles:
    - palo2_ssh_tunnel

- name: Commit pending configuration changes
  hosts: firewalls

  collections:
    - paloaltonetworks.panos

  roles:
    - role: palo_commit
