---
- name: Create POP3 Secure port
  paloaltonetworks.panos.panos_service_object:
    provider: "{{ panos_provider }}"
    name: "{{ app_type_mappings.fw_pop3_secure.palo_service[0] }}"
    protocol: "tcp"
    destination_port: "{{ app_type_mappings.fw_pop3_secure.ports[0] }}"
  when: groups['fw_pop3_secure'] | default([]) | length > 0
