---
- name: Create Splunk web port
  paloaltonetworks.panos.panos_service_object:
    provider: "{{ panos_provider }}"
    name: "{{ app_type_mappings.fw_splunk_web.palo_service[0] }}"
    protocol: "tcp"
    destination_port: "{{ app_type_mappings.fw_splunk_web.ports[0] }}"
  when: groups['fw_splunk'] | default([]) | length > 0
